<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-i37-9Z1F2P2-w11x64" failures="2" tests="11" name="----DemoTest----" time="0.223" errors="0" timestamp="2025-03-31T13:29:20 IST">
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test1" time="0.035">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests.test1(S3_MyTests.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests.test2(S3_MyTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="RetryingTheFailedTestMethods_using_IAnnotationTranformerInterface.S3_MyTests" name="test3" time="0.005"/>
</testsuite> <!-- -DemoTest- -->
