<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-i37-9Z1F2P2-w11x64" failures="2" tests="5" name="Test" time="0.707" errors="0" timestamp="2025-06-04T15:57:11 IST">
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA" name="testCase1" time="0.029">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA.testCase1(S1_ClassA.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S1_ClassA" name="testCase2" time="0.004"/>
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB" name="testCase3" time="0.002"/>
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB" name="testCase4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S2_ClassB.testCase4(S2_ClassB.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase classname="ReRun4_Failed_TCs_using_TestNgFailedXMLfile.S3_RunnerFileToExecuteFailedTCsThroughScript" name="runFailTestCases" time="0.585"/>
</testsuite> <!-- Test -->
